### ISSUE TITLE
How is the files transffered?

### ISSUE THREAD

**Issue by ikp-773** [mannprerak2/nearby_connections#14]
Hi, I am trying to work with nearby_connections. I wanted to know if the files are transferred over WiFi or Bluetooth.

**Comment by mannprerak2** [comment]
The underlying android Nearby connections API automatically handles these things. It will automatically switch between bluetooth or wifi direct or using a hotspot. This isn't something you can control.
Just be sure to use the correct [Strategy](https://pub.dev/documentation/nearby_connections/latest/nearby_connections/Strategy-class.html) as per your  needs. otherwise you will not get good transfer speeds.
For proper details check out the [readme](https://pub.dev/documentation/nearby_connections/latest/#sending-file-payload)

**Comment by ikp-773** [comment]
Thank You🙌😊
