### ISSUE TITLE
All permission convenience methods should return Future<bool>

### ISSUE THREAD

**Issue by JFtechOfficial** [mannprerak2/nearby_connections#48]
askLocationPermission can be awaited to check if the user didn't allow location access. 
On the other hand askBluetoothPermission, for example, can't be awaited and doesn't return any value so the app doesn't know whether the user has accepted or not and can't respond to it.

**Comment by mannprerak2** [comment]
That does make sense, and at one point I did think about adding it.

However, now I [recommend](https://github.com/mannprerak2/nearby_connections#you-can-use-the-permission_handler-package-to-handle-all-these-permissions) using another package for handling permissions. (See https://pub.dev/packages/permission_handler)
This is because permissions are ever evolving and may need to handled for differently for other Android/iOS versions.
