### ISSUE TITLE
cant find any docs on how to handle disconnect cases

### ISSUE THREAD

**Issue by LScodeblack** [mannprerak2/nearby_connections#53]
turning off bluetooth dosent seem to fire any disconnect callbacks, but turning of wifi does.
how can i check when bluetooth disconnected ?

**Comment by mannprerak2** [comment]
Afaik bluetooth is only used initially by nearby connections, further communications may no longer use Bluetooth and only work with Wifi if the devices support it 

This is why there's probably no callback since the devices did not really disconnect. You should verify this by sending a message after turning Bluetooth off.

If you are looking for a way to check if another device turned off its Bluetooth at a later point, you can simply listen to Bluetooth state (via another package) and send it's state as a message to the connected device.

**Comment by LScodeblack** [comment]
Awesome will do thanks for the reply !
