### ISSUE TITLE
Huawei P8 Lite under Android 7 can discover but can't advertise

### ISSUE THREAD

**Issue by dvr69** [mannprerak2/nearby_connections#77]
I'm trying the library with the example that is given with it. I have a Huawei P8 Lite under Android 7, and a Huawei Mate 20 Pro under Android 12. With Android 7 as the discoverer, and Android 12 as the advertiser, it works fine. But if Android 7 is the advertiser, and Android 12 the discoverer, no advertiser is seen by the Android 12 phone. Is there a reason for that ?

**Comment by mannprerak2** [comment]
Hmm.. not sure, it could be some deep compatibility issue due to different android versions.

But that's probably a strech. Maybe try swapping out the Android 7 device with another android version, if it works then its a compatibility issue otherwise its just a missing permission or something on then Android 12 device.

**Comment by dvr69** [comment]
Thank you for your answer. I tried with a tablet under Android 12 instead of the phone with Android 7, and both can advertise and doscover. I foudn a solution for my project to work, I simultaneously advertise and discover, like in this example given by Google : https://github.com/android/connectivity-samples/tree/main/NearbyConnectionsWalkieTalkie. The first one who discovers the other stops advertising and discovery, and initializes the connection. This way, everything works.

**Comment by mannprerak2** [comment]
Great :D

Closing this now...
