### ISSUE TITLE
Return Future<bool> in askLocationPermission

### ISSUE THREAD

**Issue by mannprerak2** [mannprerak2/nearby_connections#9]
Change the return type of askLocationPermission function from `void` to `Future<bool>`.
Return `true` if the user grants permission, `false` otherwise.

**Comment by vaishnavmhetre** [comment]
Can we have this Future return type for askExternalStoragePermission? I'm facing issue where it is setting false until I complete setting my permission, hence by button stays enabled.

There's no issue with it - just that I have to click the button again in order to subtitute the value to Observable and then the button disables.

**Comment by mannprerak2** [comment]
Hi @vaishnavmhetre 
These functions are merely for convience, you can actually use any other permission handler package to achieve the same. (Infact that's something I will recommend)

However, I'd be happy to accept a PR, if you'd like to work on this.
